/**
 * Gemini client helpers for memento-mcp.
 *
 * REST API is preferred when GEMINI_API_KEY is configured.
 * CLI remains available as a fallback and for environments without API access.
 */

import fetch from "node-fetch";
import { execFileSync, spawn } from "child_process";
import { logError, logInfo } from "./logger.js";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";
const GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta";
const DEFAULT_MODEL = process.env.GEMINI_MODEL || "gemini-3.1-flash-lite-preview";
const DEFAULT_TIMEOUT_MS = Number(process.env.GEMINI_API_TIMEOUT_MS || 30_000);
const DEFAULT_RETRY_LIMIT = Number(process.env.GEMINI_API_RETRY_LIMIT || 3);
const DEFAULT_RETRY_DELAY_MS = Number(process.env.GEMINI_API_RETRY_DELAY_MS || 1_500);

let geminiCliCached = null;

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function stripJsonFence(raw = "") {
  return String(raw).replace(/```json\s*|\s*```/g, "").trim();
}

function isRetryableGeminiStatus(status) {
  return status === 429 || status === 500 || status === 503;
}

function getWhichCommand() {
  return process.platform === "win32" ? "where.exe" : "which";
}

export async function generateContent(prompt, options = {}) {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY environment variable is not set");
  }

  const model = options.model || DEFAULT_MODEL;
  const temperature = options.temperature ?? 0.7;
  const maxTokens = options.maxTokens || 8000;
  const timeoutMs = Number(options.timeoutMs || DEFAULT_TIMEOUT_MS);
  const retryLimit = Math.max(1, Number(options.retryLimit || DEFAULT_RETRY_LIMIT));
  const retryDelayMs = Math.max(0, Number(options.retryDelayMs || DEFAULT_RETRY_DELAY_MS));
  const url = `${GEMINI_BASE_URL}/models/${model}:generateContent`;

  const requestBody = {
    contents: [
      {
        parts: [
          {
            text: prompt
          }
        ]
      }
    ],
    generationConfig: {
      temperature,
      maxOutputTokens: maxTokens,
      topP: 0.95,
      topK: 40
    },
    safetySettings: [
      { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
    ]
  };

  for (let attempt = 1; attempt <= retryLimit; attempt += 1) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": GEMINI_API_KEY
        },
        body: JSON.stringify(requestBody),
        signal: controller.signal
      });

      if (!response.ok) {
        const errorText = await response.text();
        if (attempt < retryLimit && isRetryableGeminiStatus(response.status)) {
          logInfo(`[gemini] retrying generateContent (${attempt}/${retryLimit}) with model=${model}: HTTP ${response.status}`);
          await sleep(retryDelayMs * attempt);
          continue;
        }
        throw new Error(`Gemini API error: ${response.status} ${errorText}`);
      }

      const data = await response.json();
      const parts = data?.candidates?.[0]?.content?.parts || [];
      const text = parts.map((part) => part?.text || "").join("").trim();
      if (!text) {
        throw new Error("No content generated by Gemini");
      }
      return text;
    } catch (error) {
      if (attempt < retryLimit && error?.name === "AbortError") {
        logInfo(`[gemini] retrying generateContent (${attempt}/${retryLimit}) with model=${model}: timeout after ${timeoutMs}ms`);
        await sleep(retryDelayMs * attempt);
        continue;
      }
      throw error;
    } finally {
      clearTimeout(timer);
    }
  }

  throw new Error(`Gemini generateContent failed after ${retryLimit} attempts`);
}

export async function isGeminiCLIAvailable() {
  if (GEMINI_API_KEY) return true;
  if (geminiCliCached !== null) return geminiCliCached;
  try {
    execFileSync(getWhichCommand(), ["gemini"], { stdio: "ignore", timeout: 5000 });
    geminiCliCached = true;
  } catch {
    geminiCliCached = false;
  }
  return geminiCliCached;
}

export async function geminiCLIJson(prompt, options = {}) {
  if (GEMINI_API_KEY) {
    const raw = await generateContent(prompt, {
      temperature: 0,
      maxTokens: options.maxTokens || 2000,
      timeoutMs: options.timeoutMs,
      retryLimit: options.retryLimit,
      retryDelayMs: options.retryDelayMs,
      model: options.model
    });
    return JSON.parse(stripJsonFence(raw));
  }

  const raw = await runGeminiCLI("", prompt, {
    timeoutMs: options.timeoutMs || 30_000,
    model: options.model
  });
  return JSON.parse(stripJsonFence(raw));
}

export async function runGeminiCLI(stdinContent, prompt, options = {}) {
  const timeoutMs = options.timeoutMs || 360_000;

  return new Promise((resolve, reject) => {
    const args = ["-p", prompt, "--output-format", "text", "-y"];
    const model = options.model || DEFAULT_MODEL;
    if (model) args.push("--model", model);

    const proc = spawn("gemini", args, {
      env: { ...process.env },
      stdio: ["pipe", "pipe", "pipe"]
    });

    let stdout = "";
    let stderr = "";
    let settled = false;

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      proc.kill("SIGTERM");
      reject(new Error(`Gemini CLI timed out after ${timeoutMs}ms`));
    }, timeoutMs);

    proc.stdout.on("data", (data) => {
      stdout += data.toString();
    });
    proc.stderr.on("data", (data) => {
      stderr += data.toString();
    });

    proc.on("close", (code) => {
      clearTimeout(timer);
      if (settled) return;
      settled = true;
      if (code !== 0) {
        reject(new Error(`Gemini CLI exited with code ${code}: ${stderr.trim()}`));
        return;
      }
      resolve(stdout.trim());
    });

    proc.on("error", (err) => {
      clearTimeout(timer);
      if (settled) return;
      settled = true;
      logError(`[gemini] spawn error: ${err.message}`, err);
      reject(new Error(`Gemini CLI spawn error: ${err.message}`));
    });

    if (stdinContent) {
      proc.stdin.write(stdinContent, "utf8");
    }
    proc.stdin.end();
  });
}
